### ISSUE TITLE
Custom server not pushing notifications

### ISSUE THREAD

**Issue by MayhemBill** [milesmcc/LibreNews-Server#13]
The stock LibreNews app connects to my api, but it doesn't give notifications to the app, nor do I have the option to select my categories under the channels tab, do I have to build the app myself for it to work with my server?

**Comment by milesmcc** [comment]
What is your server URL so I can test on my own device to replicate the issue?

**Comment by MayhemBill** [comment]
I *think* it is set to https://news.divisiontwentyfive.com/api 

at least the main page is set at https://news.divisiontwentyfive.com

**Comment by milesmcc** [comment]
Try changing the channel name to `Breaking News` instead of `Crew`. If this fixes it, go on over to the [client repository](https://github.com/milesmcc/LibreNews-Android) and create an issue. I'll push a fix for you as soon as I can.

**Comment by milesmcc** [comment]
See also: https://github.com/milesmcc/LibreNews-Server/issues/7

**Comment by MayhemBill** [comment]
Well I changed it to how you said, if it pushes notifications I'll let you know.

**Comment by MayhemBill** [comment]
That was indeed the issue.
