### ISSUE TITLE
How to find other servers ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [milesmcc/LibreNews-Server#16]
Hi :)
I'm using librenews on my android phone and I really don't understand something.

Currently I receive updates from the bbc and was wondering how I could find other servers to connect to. See, the news from the bbc is not really relevant to me or my country.

So, what didn't I understand about librenews ? :D

**Comment by nonbinary** [comment]
It is possible to run your own server, if you have the know-how. In the future, it would be great if there was a listing of servers. At the moment it seems no such listing exists.

**Comment by milesmcc** [comment]
So I think a server list is a great idea! As an interim solution, I added a section to the README: https://github.com/milesmcc/LibreNews-Server/blob/master/README.md#13-server-list

This should solve the server discovery problem (and therefore I'll close this issue), but I still need to encourage other people to actually _run_ their own servers...
