### ISSUE TITLE
404 when behind nginx proxy

### ISSUE THREAD

**Issue by nonbinary** [milesmcc/LibreNews-Server#19]
I'm trying to run the server behind an nginx proxy. I've added x-real-ip headers through nginx, and inspected the requests that make it to the server.
When I curl the server manually at port 8888, I get the proper webpage. When I try it through nginx (with letsencrypt certificates), I only get a 404 message.

the relevant passage in nginx.conf is:

        location ~ /librenews {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $the_host/librenews;
            proxy_set_header X-Forwarded-Proto $the_scheme;
            proxy_pass http://librenews-server-address:8888;
        }

I'm not sure on all of these posts, as they're copy-pasted from another setup.
After dumping the request headers to the log, I can see that x-forwarded proto is accepted as https, x-forwarded-for and x-real-ip are the address of my client making the request. host is the host fqdn, x-forwarded-host is read as host-fqdn/librenews

I get no error message in the logs, so have nothing to go on here.

**Comment by milesmcc** [comment]
Make sure the `/librenews` isn't being passed as part of the `proxy_pass`, as this will confuse LibreNews. Make sure nginx is chopping that part off. Is that the issue?

**Comment by nonbinary** [comment]
No, it seems not. I had the subpath in the X-Forwarded-Host header, but after removing that, I still get the 404, and no error message.

**Comment by milesmcc** [comment]
That's odd. It might be worth putting in a debug line so that you can see exactly what URLs are being requested?

**Comment by nonbinary** [comment]
Ah, there we are. Yep, the librenews sub-path is still getting sent through. I'll fix my nginx configuration and look some more.
Personally, I'd keep some debug lines there. Or possibly have a log level setting? If I have the time, I might make a pull request, but not sure when that'll be...

**Comment by nonbinary** [comment]
Yep, that fixed it. However, js and such does not work. The librenews server puts links and such from the root that it knows about. Hence, all static files are fetched from fqdn/static, and not fqdn/librenews/static, where they are actually served, atm.
I'll move my server to a separate subdomain, I think. But later. Now I'll celebrate that it looks like I'm getting my notifications to my phone :)

**Comment by milesmcc** [comment]
Well, I'm very glad that you got your own server set up. Create a separate issue for the js stuff and I'll fix that when I can...

...or you could submit a pull request! The latter would be awesome!

**Comment by nonbinary** [comment]
Oh right!
Here's the nginx setup that works, at least in part. the rewrite breaks internal links and static files, but gets the service up and running:

        location /librenews {
            rewrite /librenews/?(.*) /$1  break;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $the_host/librenews;
            proxy_set_header X-Forwarded-Proto $the_scheme;
            proxy_pass http://LIBRENEWS-SERVER-IP:8888;
        }

Just replace the caps with your actual IP address/fqdn.

**Comment by nonbinary** [comment]
A note btw: setting the x-forwarded-host to include the librenews subpath does not break the librenews webserver. Probably should use that for a future update of the internal links.
I am, sadly, very new to tornado. I kinda know my way around Python, but tornado is new to me, so I probably won't be able to swing any good pull requests there in the forseeable future.
