### ISSUE TITLE
Update requirements.txt?

### ISSUE THREAD

**Issue by nonbinary** [milesmcc/LibreNews-Server#21]
When installing my own server, I discovered that I needed to install the following packages through pip (when installing on debian stretch):

    pytz
    pycountry
    humanize
    geoip
    python-geoip-geolite2

Should they perhaps be listed in requirements.txt? It was a bit of trial & error to get the proper requirements in. Streamlining it would help less experienced users up and running.

**Comment by milesmcc** [comment]
Fixed as of 2265ee128e8feb1b3f504ed783f50ce43ac6e6d4
