### ISSUE TITLE
Why mention http connections in the readme?

### ISSUE THREAD

**Issue by mueller-ma** [milesmcc/LibreNews-Server#4]
From the readme:

> For production servers, it's heavily recommended that you use nginx as a reverse proxy. That way, you'll be able to accept standard HTTP and HTTPS requests on ports 80 and 443, respectively.

The Android app does not accept http request so it should be mentioned here that http is useless and unsecure.

**Comment by milesmcc** [comment]
I will add. Thank you for pointing this out.

**Comment by milesmcc** [comment]
https://github.com/milesmcc/LibreNews-Server/commit/9ed02fa3e2db412aaedd3deac0edfff17160f1b4
