### ISSUE TITLE
Minify api result

### ISSUE THREAD

**Issue by mueller-ma** [milesmcc/LibreNews-Server#5]
I have made an api request an got an answer with 7.9K. I have removed unneeded spaces and reduced it that way to 5.9K.
When removing linebreaks even more traffic can be saved. This is, when sync every 5 minutes, about 17MB per month.

**Comment by milesmcc** [comment]
Resolved in https://github.com/milesmcc/LibreNews-Server/commit/d1eefd15b75a17af46bb62f1090bfde5cf961d8e and https://github.com/milesmcc/LibreNews-Server/commit/51f0b281cf6b8dacd9d76912b1e10855c54ceaec

Thanks for the request!
