### ISSUE TITLE
FR: Return only new news

### ISSUE THREAD

**Issue by mueller-ma** [milesmcc/LibreNews-Server#6]
E.g. librenews.io/api?last-id=1234 only returns news newer than the news with id 1234

Apart from that: have you thougth about reducing the amount of returned news? Currently I get news which are up to 5 days old. Since the maximum sync rate is 24h these old news are not really needed and waste traffic.

**Comment by milesmcc** [comment]
See https://github.com/milesmcc/LibreNews-Server/commit/f776d12bb0e0c2baa4deed4f26ccc9b3d4ada308 — something like that?

**Comment by milesmcc** [comment]
Just so you know, the default LibreNews server now supports the `latest` parameter. For example: https://librenews.io/api?latest=891955250768351232

While this hasn't yet been implemented in the client, I will soon have the client include the latest flash it has received in its GET request to minimize data usage.

**Comment by mueller-ma** [comment]
Great job!
